[package]
name = "awsctx"
version = "0.2.0"
authors = ["Hironoiri Yamamoto <mr.nikoru918@gmail.com>"]
edition = "2018"
description = "Context Manager for AWS Profiles"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.55"
clap = "3.1.5"
dirs = "4.0.0"
regex = "1.5.4"
skim = "0.9.4"
thiserror = "1.0.30"
