[package]
name = "ctxm"
version = "0.1.0"
authors = ["Hironoiri Yamamoto <mr.nikoru918@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
dirs = "3.0.1"
thiserror = "1.0"
regex = "1"
clap = "2.33.3"
