[package]
name = "awsctx"
version = "0.3.1"
authors = ["Hironori Yamamoto <mr.nikoru918@gmail.com>"]
edition = "2018"
description = "Context Manager for AWS Profiles"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.56"
clap = { version = "3.1.9", features = ["derive"] }
clap_complete = "3.1.1"
dirs = "4.0.0"
regex = "1.5.5"
skim = "0.9.4"
thiserror = "1.0.30"
