[package]
authors = ["Hironori Yamamoto <mr.nikoru918@gmail.com>"]
description = "Context Manager for AWS Profiles"
edition = "2021"
license = "MIT"
name = "awsctx"
version = "0.4.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.57"
clap = {version = "3.1.15", features = ["derive"]}
clap_complete = "3.1.3"
config = "0.13.1"
dirs = "4.0.0"
handlebars = "4.2.2"
log = "0.4.17"
once_cell = "1.10.0"
regex = "1.5.5"
serde = {version = "1.0.137", features = ["derive"]}
serde_derive = "1.0.137"
serde_json = "1.0.80"
serde_yaml = "0.8.23"
simplelog = {version = "0.12.0", features = ["paris", "ansi_term"]}
skim = "0.9.4"
thiserror = "1.0.31"
