name: homebrew-release
on:
  workflow_run:
    workflows:
      - release
    types:
      - completed
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: false
        description: tag version to release

env:
  USER_NAME: hiro-o918
  REPO_NAME: awsctx

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: extract version
        id: extract-version
        run: |
          if [[ "${{  github.event.inputs.tag }}" != "" ]]
          then
            printf "::set-output name=TAG-NAME::${{  github.event.inputs.tag }}\n"
          else
            printf "::set-output name=%s::%s\n" TAG-NAME "${GITHUB_REF#refs/tags/}"
          fi
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: ${{ env.REPO_NAME }}
          formula-path: Formula/${{ env.REPO_NAME }}.rb
          homebrew-tap: ${{ env.USER_NAME }}/homebrew-tap
          base-branch: main
          tag-name: ${{ steps.extract-version.outputs.TAG-NAME }}
          download-url: https://github.com/${{ env.USER_NAME }}/${{ env.REPO_NAME }}/releases/download/${{ steps.extract-version.outputs.TAG-NAME }}/awsctx_${{ steps.extract-version.outputs.TAG-NAME }}_x86_64-apple-darwin.tar.gz

        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
